spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: local
  jackson:
    default-property-inclusion: non_null
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

multitenant:
  defaultTenant: public

management:
  endpoints:
    web:
      exposure:
        include: beans,health,httptrace
